import { Big_Shoulders_Inline_Display, Lobster } from "next/font/google";
import "ui/styles";
const inter = Big_Shoulders_Inline_Display({
  subsets: ["latin"],
  variable: "--font-sans",
});

const lobster = Lobster({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-serif",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lobster.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
